### 1. הרשמה של משתמש חדש
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test2@example.com",
  "password": "User123",
  "confirmPassword": "User123"
}

###

### 2. התחברות וקבלת access + refresh token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "User123"
}

###

### 3. קבלת access token חדש לפי refresh token (נשלח מה-cookie)
GET http://localhost:5000/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2VmZDhkNTcyYTU5OTVhYzA1Nzg2MzciLCJpYXQiOjE3NDM3NzI5ODEsImV4cCI6MTc0NDM3Nzc4MX0.YS25KMr9XJx4vHFdRGxPqpw5HoNX6uXS4xZVOB7Hzeo"
}

###

### 4. התנתקות – מחיקת refresh token מה-DB ומה-cookie
POST http://localhost:5000/api/auth/logout

###

### יצירת סקריפט job-alert חדש
POST http://localhost:5000/api/scripts/generate-job-alert
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2YwZmM1Nzk1YjM1NmZmMTBiZjMxZTQiLCJpYXQiOjE3NDM4NDY1MTIsImV4cCI6MTc0Mzg0NzQxMn0.c5jlhs4WOOz6JpCp_je_WI6D25TBCHnF0YAOR1Ytxno
Content-Type: application/json

{
  "serpApiKey": "9a0bbc760bc361ad3e18040140ee489492f4ac6b2c4deb48d265785f520061af",
  "emailSender": "roiyraz88@gmail.com",
  "emailPassword": "gkug zzma ihjn tumt",
  "emailRecipient": "roiyraz88@gmail.com",
  "query": "site:comeet.com/jobs junior"
}
